// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package latexmk

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// WorkspaceClient is the client API for Workspace service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkspaceClient interface {
	New(ctx context.Context, in *Args, opts ...grpc.CallOption) (*WS, error)
	Close(ctx context.Context, opts ...grpc.CallOption) (Workspace_CloseClient, error)
}

type workspaceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkspaceClient(cc grpc.ClientConnInterface) WorkspaceClient {
	return &workspaceClient{cc}
}

func (c *workspaceClient) New(ctx context.Context, in *Args, opts ...grpc.CallOption) (*WS, error) {
	out := new(WS)
	err := c.cc.Invoke(ctx, "/latexmk.Workspace/New", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceClient) Close(ctx context.Context, opts ...grpc.CallOption) (Workspace_CloseClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Workspace_serviceDesc.Streams[0], "/latexmk.Workspace/Close", opts...)
	if err != nil {
		return nil, err
	}
	x := &workspaceCloseClient{stream}
	return x, nil
}

type Workspace_CloseClient interface {
	Send(*WS) error
	CloseAndRecv() (*Empty, error)
	grpc.ClientStream
}

type workspaceCloseClient struct {
	grpc.ClientStream
}

func (x *workspaceCloseClient) Send(m *WS) error {
	return x.ClientStream.SendMsg(m)
}

func (x *workspaceCloseClient) CloseAndRecv() (*Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// WorkspaceServer is the server API for Workspace service.
// All implementations must embed UnimplementedWorkspaceServer
// for forward compatibility
type WorkspaceServer interface {
	New(context.Context, *Args) (*WS, error)
	Close(Workspace_CloseServer) error
	mustEmbedUnimplementedWorkspaceServer()
}

// UnimplementedWorkspaceServer must be embedded to have forward compatible implementations.
type UnimplementedWorkspaceServer struct {
}

func (UnimplementedWorkspaceServer) New(context.Context, *Args) (*WS, error) {
	return nil, status.Errorf(codes.Unimplemented, "method New not implemented")
}
func (UnimplementedWorkspaceServer) Close(Workspace_CloseServer) error {
	return status.Errorf(codes.Unimplemented, "method Close not implemented")
}
func (UnimplementedWorkspaceServer) mustEmbedUnimplementedWorkspaceServer() {}

// UnsafeWorkspaceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkspaceServer will
// result in compilation errors.
type UnsafeWorkspaceServer interface {
	mustEmbedUnimplementedWorkspaceServer()
}

func RegisterWorkspaceServer(s grpc.ServiceRegistrar, srv WorkspaceServer) {
	s.RegisterService(&_Workspace_serviceDesc, srv)
}

func _Workspace_New_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Args)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServer).New(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/latexmk.Workspace/New",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServer).New(ctx, req.(*Args))
	}
	return interceptor(ctx, in, info, handler)
}

func _Workspace_Close_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorkspaceServer).Close(&workspaceCloseServer{stream})
}

type Workspace_CloseServer interface {
	SendAndClose(*Empty) error
	Recv() (*WS, error)
	grpc.ServerStream
}

type workspaceCloseServer struct {
	grpc.ServerStream
}

func (x *workspaceCloseServer) SendAndClose(m *Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *workspaceCloseServer) Recv() (*WS, error) {
	m := new(WS)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Workspace_serviceDesc = grpc.ServiceDesc{
	ServiceName: "latexmk.Workspace",
	HandlerType: (*WorkspaceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "New",
			Handler:    _Workspace_New_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Close",
			Handler:       _Workspace_Close_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "latexmk.proto",
}
